### ISSUE TITLE
Retrieving SIM card information for multiple SIM cards.

### ISSUE THREAD

**Issue by MurageKabui** [EYALIN/community-cordova-plugin-sim#1]
Hello @EYALIN !

 I wanted to give you some feedback on your plugin and ask for your help with a particular problem. First off, I managed to set up the necessary permissions correctly to access SIM card information in my project.

However, I've hit a roadblock. Even though the permissions are in place, I'm facing a limitation. The return object I receive from the plugin doesn't include the "cards" array. Right now, I can only fetch limited details like the carrier name, country code, and a few others:

```json
{
  "carrierName": "Safaricom",
  "countryCode": "ke",
  "mcc": "639",
  "mnc": "07",
  "dataActivity": 0,
  "phoneType": 1,
  "simState": 5,
  "isNetworkRoaming": false,
  "phoneCount": 2,
  "activeSubscriptionInfoCount": 0,
  "activeSubscriptionInfoCountMax": 2,
  "defaultDataSubscriptionId": 4
}
```

Since my goal is to retrieve information for both SIM cards, I was wondering if you could suggest an alternative approach or provide additional steps to help me obtain the necessary data for both SIM cards.

I appreciate your support and guidance in resolving this issue. Thank you for taking the time to look into it.

Best regards,
Murage Kabui

**Comment by EYALIN** [comment]
@MurageKabui i will try to investigate in the next days how we can handle both sim cards

**Comment by MurageKabui** [comment]
> @MurageKabui i will try to investigate in the next days how we can handle both sim cards

Any progress with this?

**Comment by EYALIN** [comment]
@MurageKabui not at the moment. we have some plugins that need to be refactored for Android target 33, and they have more priority. so i guess it will take time to change it in order to support 2 sims

**Comment by opindia123** [comment]
Dear @EYALIN  ,
Any update on Multiple SIM detection fail, also PhoneNumber is not in json structure. 

Getting below error : 

java.lang.SecurityException: Need READ_PHONE_STATE, READ_PRIVILEGED_PHONE_STATE, or carrier privilege
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3340)
	at android.os.Parcel.createException(Parcel.java:3324)
	at android.os.Parcel.readException(Parcel.java:3307)
	at android.os.Parcel.readException(Parcel.java:3249)
	at com.android.internal.telephony.ISub$Stub$Proxy.getActiveSubInfoCount(ISub.java:1670)
	at android.telephony.SubscriptionManager.getActiveSubscriptionInfoCount(SubscriptionManager.java:2329)
	at com.pbakondy.Sim.execute(Sim.java:93)
	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
	at org.apache.cordova.PluginManager.exec(PluginManager.java:146)
	at com.getcapacitor.MessageHandler.lambda$callCordovaPluginMethod$2(MessageHandler.java:154)
	at com.getcapacitor.MessageHandler.$r8$lambda$NhJ0d2egplsDIA6X_OJM4sa5L1w(Unknown Source:0)
	at com.getcapacitor.MessageHandler$$ExternalSyntheticLambda2.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.os.HandlerThread.run(HandlerThread.java:85)
android.telephony.TelephonyManager@c78e310

I have added only READ_PHONE_STATE permission .

Build config is 
 minSdkVersion = 26
    compileSdkVersion = 35
    targetSdkVersion = 35

Testing is on Android 13, 12 Both have same result.

Thanks
Om

**Comment by EYALIN** [comment]
Thanks for the detailed report. The JSON you pasted is the old upstream plugin's shape (flat `carrierName`/`countryCode`, no `cards`). This fork (`community-cordova-plugin-sim` 1.5.0+) already returns a `cards` array with one entry per active SIM — see `SimPlugin.java`, which iterates `SubscriptionManager.getActiveSubscriptionInfoList()` and includes `carrierName`, `countryCode`, `mcc`, `mnc`, `simSlotIndex`, `subscriptionId` and more per card. If you install this package and call `getSimInfo()`, you should get both SIMs under `result.cards`.

@opindia123 your stack trace points at `com.pbakondy.Sim` — that's the old plugin, not this fork. Note that fields like `phoneNumber`/`simSerialNumber` require `READ_PHONE_NUMBERS` (or carrier privilege) on newer Android in addition to `READ_PHONE_STATE`. Could you confirm which package/version you have installed and which fields you need? With that I can advise further. Answered for the multi-SIM question; leaving open pending confirmation you're on this fork.
